name: CI of CentroidalControlCollection (colcon)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Install clang-format-14
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install clang-format-14
      - name: Run clang-format-check
        run: |
          ./.clang-format-check.sh

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        mc-rtc-version: [head, stable]
        exclude:
          - build-type: Debug
            mc-rtc-version: stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set environment variables
        run: |
          set -e
          set -x
          echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV 
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ] && \
             [ "${{ matrix.build-type }}" == "RelWithDebInfo" ] && \
             [ "${{ github.repository_owner }}" == "isri-aist" ] && \
             [ "${{ github.ref }}" == "refs/heads/master" ]
          then
            echo "UPLOAD_DOCUMENTATION=true" >> $GITHUB_ENV
            sudo apt-get install -qq doxygen graphviz
          else
            echo "UPLOAD_DOCUMENTATION=false" >> $GITHUB_ENV
          fi
      - name: Install ROS2
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          ros: |
            apt: ros-base
      - name: Install Dependencies
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          build-type: ${{ matrix.build-type }}
          ubuntu: |
            apt-mirrors:
              mc-rtc:
                cloudsmith: mc-rtc/head
            apt: cmake libgtest-dev libeigen-qld-dev libmc-rtc-dev libqpsolvercollection-dev libforcecontrolcollection-dev
      - name: Setup colcon workspace
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/colcon_ws/src/
          cd ${GITHUB_WORKSPACE}/colcon_ws
          set +x
          . /opt/ros/${ROS_DISTRO}/setup.bash

      # - name: Checkout repository code
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: recursive
      #     path: catkin_ws/src/CentroidalControlCollection
      # - name: Checkout QpSolverCollection
      #   uses: actions/checkout@v2
      #   with:
      #     repository: isri-aist/QpSolverCollection
      #     submodules: recursive
      #     path: catkin_ws/src/QpSolverCollection
      # - name: Checkout ForceControlCollection
      #   uses: actions/checkout@v2
      #   with:
      #     repository: isri-aist/ForceControlCollection
      #     submodules: recursive
      #     path: catkin_ws/src/ForceControlCollection
      - name: Checkout NMPC
        uses: actions/checkout@v2
        with:
          repository: nqtabokado/NMPC
          ref: feature/fix-unable-to-build-sub-packages-on-ros2
          submodules: recursive
          path: colcon_ws/src/NMPC
      # - name: Rosdep install
      #   run: |
      #     set -e
      #     set -x
      #     cd ${GITHUB_WORKSPACE}/catkin_ws
      #     set +x
      #     . devel/setup.bash
      #     set -x
      #     sudo rosdep init
      #     rosdep update
      #     rosdep install -y -r --from-paths src --ignore-src
      - name: Colcon build nmpc_ddp
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/colcon_ws
          set -x
          colcon build --packages-select nmpc_ddp --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DAMENT_CMAKE_UNINSTALL_TARGET=OFF

      # - name: Run tests
      #   run: |
      #     set -e
      #     set -x
      #     cd ${GITHUB_WORKSPACE}/catkin_ws
      #     set +x
      #     . devel/setup.bash
      #     set -x
      #     catkin build --limit-status-rate 0.1 --catkin-make-args run_tests -- centroidal_control_collection --no-deps
      #     catkin_test_results --verbose --all build
      - name: Upload documentation
        # Only run for one configuration and on origin master branch
        if: matrix.os == 'ubuntu-22.04' && matrix.build-type == 'RelWithDebInfo' && matrix.mc-rtc-version == 'head' && github.repository_owner == 'isri-aist' && github.ref == 'refs/heads/master'
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws/src/CentroidalControlCollection
          git config --global user.name "Masaki Murooka"
          git config --global user.email "m-murooka@aist.go.jp"
          git remote set-url origin "https://mmurooka:${{ secrets.CI_TOKEN }}@github.com/isri-aist/CentroidalControlCollection"
          git fetch --depth=1 origin gh-pages:gh-pages
          git checkout --quiet gh-pages
          rm -rf doxygen/ cmake/
          cp -r ${GITHUB_WORKSPACE}/catkin_ws/build/centroidal_control_collection/doc/html/ doxygen
          git add doxygen
          git_status=`git status -s`
          if test -n "$git_status"; then
            git commit --quiet -m "Update Doxygen HTML files from commit ${{ github.sha }}"
            git push origin gh-pages
          else
            echo "Github pages documentation is already up-to-date."
          fi
